Repository WildCodeSchool/2023-03-JS-TLSE-P2-pokedev, pull requests merged in 2023-04, with the labels that each got.

#1 S03_U01 installed package npm and add logos
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/LogoDark.png
  frontend/src/assets/LogoLight.png
  frontend/src/assets/LogoMedium.png
  frontend/src/components/Counter.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Pokemain.jsx
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#2 So3 u02 home
  frontend/postcss.config.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Home.css
  frontend/src/assets/arrow.svg
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/auto-text.json
  frontend/tailwind.config.js
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#3 S03_U03_SideBarTop First commit to sidebar, add filter button and tog…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/FilterAndToggle.jsx
  frontend/src/components/FilterCategory.jsx
  frontend/src/components/SidebarTop.jsx
  frontend/src/components/ToggleButtonFilter.jsx
  frontend/src/css/SideBarTop.css
  frontend/src/pages/Pokemain.jsx
  package-lock.json
  package.json
Labels: Conflicts resolved

#5 fixing algo and adding both modal and card components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/loadingImg.gif
  frontend/src/components/CardProfil.jsx
  frontend/src/components/ModalProfile.jsx
  frontend/src/css/CardProfil.css
  frontend/src/css/ModalProfile.css
  frontend/src/pages/Pokemain.jsx
  package-lock.json
  package.json
Labels: Reviewed

#7 branch dev du 28.04.23 ( avec cardprofil + composant modal)
  frontend/src/css/CardProfil.css
Labels: Reviewed
